AWSTemplateFormatVersion: "2010-09-09"
Description: Product Service (node-reference)
Parameters:
  Image:
    Type: String
    Description: Docker image to run
Resources:
  Database:
    Type: "AWS::DynamoDB::Table"
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: "HASH"
      ProvisionedThroughput: 
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
  LogGroup:
    Type: "AWS::Logs::LogGroup"
    Properties:
      RetentionInDays: 30
  ECSCluster:
    Type: "AWS::ECS::Cluster"
    Properties: {}
  TaskDefinition:
    Type: "AWS::ECS::TaskDefinition"
    Properties: 
      Cpu: 256
      Memory: 512
      # ExecutionRoleArn: String
      NetworkMode: awsvpc
      # I think this is the one I want to set
      # TaskRoleArn: String
      ContainerDefinitions:
        - Name: ProductService
          Cpu: 256
          Memory: 512
     #     Environment:
     #       - KeyValuePair
          Essential: true
          Image: !Ref Image
          LogConfiguration:
            LogDriver: "awslogs"
            Options:
              "awslogs-group": !Ref LogGroup
              "awslogs-region": "us-east-1"