AWSTemplateFormatVersion: "2010-09-09"
Description: Product Service (node-reference)
Parameters:
  Image:
    Type: String
    Description: Docker image to run
Resources:
  Database:
    Type: "AWS::DynamoDB::Table"
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: "HASH"
      ProvisionedThroughput: 
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
  LogGroup:
    Type: "AWS::Logs::LogGroup"
    Properties:
      RetentionInDays: 30
  ECSCluster:
    Type: "AWS::ECS::Cluster"
    Properties: {}
  TaskRole:
    Type: "AWS::IAM::Role"
    Properties:
      ManagedPolicyArns:
      #Fix this this is horrible of course
        - "arn:aws:iam::aws:policy/AdministratorAccess"
  TaskDefinition:
    Type: "AWS::ECS::TaskDefinition"
    Properties: 
      Cpu: 256
      Memory: 512
      ExecutionRoleArn: !GetAtt TaskRole.Arn
      TaskRoleArn: !GetAtt TaskRole.Arn
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ContainerDefinitions:
        - Name: ProductService
          Cpu: 256
          Memory: 512
     #     Environment:
     #       - KeyValuePair
          Essential: true
          Image: !Ref Image
          LogConfiguration:
            LogDriver: "awslogs"
            Options:
              awslogs-group: !Ref LogGroup
              awslogs-region: "us-east-1"
              awslogs-stream-prefix: "ProductService"
  Service: 
    Type: AWS::ECS::Service
#    DependsOn: ListenerRule
    Properties: 
      Cluster: !Ref ECSCluster
      LaunchType: FARGATE
      DesiredCount: 1
      TaskDefinition: !Ref TaskDefinition
#      LoadBalancers: 
#        - ContainerName: !Sub ${ServiceName}-container
#          ContainerPort: !Ref ContainerPort
#          TargetGroupArn: !Ref TargetGroup
      NetworkConfiguration: 
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets:
            - subnet-5d24b151	
            - subnet-c5c9fded
            - subnet-aca64cdb
            - subnet-2fb7df4a
            - subnet-62d9cd24
            - subnet-a8e18192